# Generated by Django 3.1.3 on 2020-11-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='className',
            field=models.CharField(default='', max_length=100),
        ),
    ]
