# Generated by Django 3.1.3 on 2020-12-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classname',
            options={'verbose_name_plural': 'classnames'},
        ),
    ]
