# Generated by Django 3.1.3 on 2020-11-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_students_classname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='className',
        ),
    ]
